package com.impulsive.app.backend.data.local.database

import java.io.File
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class SafeExitDatabaseSchemaSourceTest {
    private val schemaFile =
        File(
            "schemas/" +
                "com.impulsive.app.backend.data.local.database." +
                "AppDatabase/14.json",
        )

    @Test
    fun schemaFourteenContainsExactSafeExitLedger() {
        assertTrue(
            "Room schema 14 must be generated by KSP.",
            schemaFile.isFile,
        )

        val database =
            JSONObject(
                schemaFile.readText(),
            )
                .getJSONObject(
                    "database",
                )

        assertEquals(
            14,
            database.getInt(
                "version",
            ),
        )

        val entity =
            database
                .getJSONArray(
                    "entities",
                )
                .let { entities ->
                    (0 until entities.length())
                        .map {
                            entities.getJSONObject(
                                it,
                            )
                        }
                        .single {
                            it.getString(
                                "tableName",
                            ) ==
                                "safe_exit_records"
                        }
                }

        val fields =
            entity
                .getJSONArray(
                    "fields",
                )
                .let { values ->
                    (0 until values.length())
                        .map {
                            values.getJSONObject(
                                it,
                            )
                        }
                }

        assertEquals(
            setOf(
                "sourceKey",
                "source",
                "sourceId",
                "completedAt",
            ),
            fields
                .map {
                    it.getString(
                        "columnName",
                    )
                }
                .toSet(),
        )

        fields.forEach { field ->
            assertEquals(
                "TEXT",
                field.getString(
                    "affinity",
                ),
            )
            assertTrue(
                field.getBoolean(
                    "notNull",
                ),
            )
        }

        assertEquals(
            listOf(
                "sourceKey",
            ),
            entity
                .getJSONObject(
                    "primaryKey",
                )
                .getJSONArray(
                    "columnNames",
                )
                .let { names ->
                    (0 until names.length())
                        .map {
                            names.getString(
                                it,
                            )
                        }
                },
        )

        val indexes =
            entity
                .getJSONArray(
                    "indices",
                )
                .let { values ->
                    (0 until values.length())
                        .map {
                            values
                                .getJSONObject(
                                    it,
                                )
                                .getString(
                                    "name",
                                )
                        }
                        .toSet()
                }

        assertEquals(
            setOf(
                "index_safe_exit_records_completedAt",
                "index_safe_exit_records_source_completedAt",
            ),
            indexes,
        )

        val columnNames =
            fields
                .map {
                    it.getString(
                        "columnName",
                    )
                        .lowercase()
                }

        listOf(
            "controlpoints",
            "action",
            "validcompletion",
            "packagename",
            "url",
            "domain",
            "article",
            "trigger",
            "journal",
            "reflection",
        ).forEach { forbidden ->
            assertFalse(
                "Safe Exit schema contains forbidden field: $forbidden",
                columnNames.any {
                    forbidden in it
                },
            )
        }
    }

    @Test
    fun migrationThirteenToFourteenIsRegisteredWithoutDestructiveFallback() {
        val source =
            File(
                "src/main/java/com/impulsive/app/" +
                    "backend/data/local/database/" +
                    "AppDatabase.kt",
            )
                .readText()

        assertTrue(
            source.contains(
                "version = 14",
            ),
        )
        assertTrue(
            source.contains(
                "Migration13To14",
            ),
        )
        assertTrue(
            source.contains(
                "Migration13To14,",
            ),
        )
        assertFalse(
            source.contains(
                "fallbackToDestructiveMigration",
            ),
        )
    }
}